services:
  deno:
    #user: ${UID}:${GID}
    build: ./docker
    image: fatecore_deno
    restart: always
    container_name: fatecore_deno
    volumes:
      - ./app/:/app
    ports:
      - 3000:3000
      - 5173:5173
    expose:
      - 3000
      - 5173
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        cd FateCore-Browser/
        deno task dev --host