services:
  deno:
    #user: ${UID}:${GID}
    build: ./docker
    image: fatecore_deno
    restart: always
    container_name: fatecore_deno
    volumes:
      - ./app/:/app
    ports:
      - 3000:3000
      - 5173:5173
      - 8000:8000
    expose:
      - 3000
      - 5173
      - 8000
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        cd FateCore-Browser/
        deno task dev
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    ## to do add persistence
    environment:
      POSTGRES_PASSWORD: NEEDTOCHANGEDENO

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080